### ISSUE TITLE
formula appears to produce inconsistent alternatives links

### ISSUE THREAD

**Issue by sroegner** [saltstack-formulas/maven-formula#14]
[root@localhost ~]# ll /usr/bin/mvn
    lrwxrwxrwx 1 root root 23 Jul 26 21:54 /usr/bin/mvn -> /etc/alternatives/maven
    [root@localhost ~]# ls -l /etc/alternatives/maven
    lrwxrwxrwx 1 root root 18 Jul 26 21:54 /etc/alternatives/maven -> /opt/maven/bin/mvn
    [root@localhost ~]# ls -l /opt/maven/bin/mvn
    ls: cannot access /opt/maven/bin/mvn: No such file or directory

@noelmcloughlin any idea?

This is CentOS6, salt 2016.3.2 (Boron)
No maven-related data in grains or pillar

**Comment by noelmcloughlin** [comment]
@sroegner I'll get this fixed, thanks.
