### ISSUE TITLE
syntax error in settings.sls

### ISSUE THREAD

**Issue by sroegner** [saltstack-formulas/maven-formula#21]
`local:
    Data failed to compile:
    ----------
    Rendering SLS 'base:maven' failed: Jinja syntax error: unexpected '}', expected ')'
    /var/cache/salt/minion/files/base/maven/settings.sls(40):
    ---
    [...]
    {%- set source_hash = default_source_hash %}
    {%- else %}
    {%- set source_hash = g.get('source_hash', p.get('source_hash', default_source_hash )) %}
    {%- endif %}

    {%- set user          = g.get('default_user', salt['pillar.get']('default_user', p.get('default_user', 
    default_user))%}    <======================
    {%- set orgdomain     = g.get('orgdomain', p.get('orgdomain', default_orgdomain )) %}
    {%- set scmhost       = g.get('scmhost', p.get('scmhost', default_scmhost )) %}
    {%- set repohost      = g.get('repohost', p.get('repohost', default_repohost )) %}
    {%- set archetypes    = g.get('archetypes', p.get('archetypes', default_archetypes )) %}`

**Comment by sroegner** [comment]
@noelmcloughlin please consider executing/testing your modified code before submitting a PR

**Comment by noelmcloughlin** [comment]
@sroegner You raised issue, assigned to @noelmcloughlin & then done your own thing without nametagging me - so I got no alerts - and done work to meet both concerns.  Then I find a PR!!!!

Today!!  2 PR and 1 Bug are gone (closed, cancelled, submitted, wtf) with no collaboration.

Please stop this behaviour - if there is a bug is settings.sls its because the PR was not discussed.

Stop this behaviour now!! @sroegner

**Comment by noelmcloughlin** [comment]
Verified on Ubuntu 17.04

**Comment by blbradley** [comment]
@noelmcloughlin 

> When I do bigger PR I do regression testing on Fedora/Suse/Ubuntu and this was not done as #20 indicates????

@sroegner mentioned that you should execute your change before submitting a PR, and I'm inclined to agree with him. I have not seen @sroegner show any bad behavior, so he does not need to 'stop'. Try not to take comments on GitHub so personally.

**Comment by noelmcloughlin** [comment]
@blbradley its not collaboration in my opinion - did you not read my summary of @sroegner behaviour above - and give your opinion on him? @whiteinge

**Comment by sroegner** [comment]
@noelmcloughlin I am sorry that there seems to be no effective way of clearing up what has to be a misunderstanding. I had to spend a lot of time lately investigating regressions introduced into a formula that happens to be part of our stack but has been unusuable to us for quite some time now. I understand that your experience might be different - i.e it working for you.

As to what you perceive as my behavior I am - again - sorry things went this way but I was following what used to be the workflow here. Having said that I do find it a reasonable expectation to have at least executed a formula/state before submitting a PR: others finding your syntax errors is simply not what the pull request process is for. 

@blbradley To not let this escalate any further I will leave the project and maintain my own fork from now on. Sorry again for the trouble

**Comment by blbradley** [comment]
@sroegner No trouble. I don't use this formula. Feel free to stay.
